### PR TITLE
Trying to update master branch

### PR DESCRIPTION
**Pull request by LiskoSlayer63**
If I accidentally did this wrong, please ignore. It's supposed to merge BluSunrize repo to my repo, not other way around.

### CODE REVIEW

**Comment by LiskoSlayer63** [comment]
@malte0811 @BluSunrize I'm sorry to bother you, but I'm not very familiar with GitHub and this says that there's confilct between our builds.. How do I merge these repositories?

**Comment by BluSunrize** [comment]
No clue mate.
This is your fork =P

**Comment by LiskoSlayer63** [comment]
@BluSunrize Damn, thanks anyway :D I'll probably just do this manually for that one file and then it should merge (I think..)

**Comment by BluSunrize** [comment]
You should really close this thing already, because it keeps pinging us when people push to IE.

**Comment by LiskoSlayer63** [comment]
@BluSunrize Didn't know everyone gets the notice. I closed it now until I have time to merge it.

**Pull request closed without merging**
